---
title: Deliverable 4 - Video Pitch
author:
    - name: Trevor Corcoran
      email: corcorantj@vcu.edu
    - name: Jon Rutan
      email: rutanj@vcu.edu
---

[[Link to repository](https://github.com/cmsc-vcu/cmsc408-sp2025-del4-open-valve/)]

# Video pitch

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1888231/sp/188823100/embedIframeJs/uiconf_id/28242191/partner_id/1888231?iframeembed=true&playerId=kplayer&entry_id=1_fwzkxu09&flashvars[streamerType]=auto" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="CMSC408-SP2025-Open_Valve-Presentation"></iframe>

[Link to source video](https://cdnapisec.kaltura.com/index.php/extwidget/preview/partner_id/1888231/uiconf_id/28242191/entry_id/1_fwzkxu09/embed/dynamic) in case the iframe player
does not work.

## Crow's Foot ER Diagram

```{mermaid}
erDiagram 
    
    GAME {
        int appID PK
        string title
        string description
        date release_date
        string store_page_link
        int game_tag_id FK
    }

    TAG {
      string name PK
      string tag_page_link
      int game_tag_id FK "multi-valued"
    }

    GENRE {
      string name PK
    }

    GAME_TAG {
      int game_tag_id PK
      int game_id FK
      int tag_name FK
    }

    USER {
      int user_id PK
      string name
    }
   
    LIBRARY {
      int user_id FK
      string appID FK "multi-valued"
    }

    GAME_TAG }o--|{ TAG : has
    GAME ||--|| GAME_TAG : has
    GENRE }o..o{ TAG : related-somehow
    USER ||..|| LIBRARY : owns
    LIBRARY }o..o{ GAME : contains
```

## Problem Domain

Open Valve is a database of steam apps and their associated game data. The focus of the database is on the user-applied tags to steam games.

## Need

The goal of our project is to utilize this data to create a curated recommendation system for users based on their game tags and relevant data.

The current recommendation system that Steam boasts is frankly lackluster. Despite being one of the largest game storefronts with millions of users and an untold number
of games, the discovery system just does not cut it. We aim to create a database and front-end to address this issue.

## Context, Scope, Perspective

We are approaching this as from the perspective of Steam users that want to spend more of our hard-earned money on video games. We do not want to extend our reach beyond what
is reasonable for a semester-long project. To this end, we are expecting to only create a basic front-end that is focused on the features, rather than presentability.
Additionally, we are first attempting to implement just one recommendation algorithm, and we will see from there what might be necessary to bring this project to fruition.

[ProtonDB](https://www.protondb.com/dashboard) is a notable example of a similar service. On the linked page, if you change the "Category" to "Personal Library", there is an option
to link your Steam account. Using your profile, the website will process your library. ProtonDB uses this information to tell you what games you own that are compatible with
Valve's Windows compatability layer called [Proton](https://github.com/ValveSoftware/Proton) (which itself is based off of [Wine](https://www.winehq.org/)). We hope to create a similar
user experience with our project.

## Motivation

As stated, we believe the discoverability of games on the Steam storefront is lacking, and we want to make a difference!

# README

::: {style="background:lightgray; margin-left:20px; border-top: 3px solid black; border-bottom: 3px solid black; padding-left:20px; padding-right:20px"}
{{< include ../README.md >}}
:::


# Reflection

What did you like the most about this project?
: Making a video was an interesting departure from the usual faire of writing textual reports. It allowed us to be creative and present our
ideas in a much more fluid manner than otherwise possible in a text document.

How are you finding Harmonize to host/facilitate discussions?  Is it helpful?
: Harmonize is difficult for discussing the class topics. It is not because of Harmonize itself, but rather the excessive reliance on ChatGPT answers. Instead of conducting a
dialogue it seems that everyone would rather just meet their post/response quota and be done. Harmonize itself is cleaner and far better structured than Canvas discussions though.

How would you improve Harmonize so that it works better for discussions?
: Discourage AI responses. While AI is clearly an invaluable tool and our futures as computer scientists will rely on it; it kills the human element of discussion and dialogue that gives the platform any value in the first place.
